//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPNREG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public int USR_ID { get; set; }
        public string DB_User { get; set; }
        public string DB_Admin { get; set; }
    }
}
